#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Generate PostGIS-compatible SQL function stubs from the sedonadb registry.
#
# Reads src/registry.rs, extracts st_* function names and their dispatch
# macro types (which encode argument arity), and generates bridge-table
# stubs with correct signatures.
#
# Output: container/init.d/0008-quackgis-generated-stubs.sql
#
# Usage:
#   ./container/generate-stubs.sh
set -euo pipefail

cd "$(dirname "$0")/.."

REGISTRY="src/registry.rs"
OUTPUT="container/init.d/0008-quackgis-generated-stubs.sql"

if [ ! -f "$REGISTRY" ]; then
    echo "ERROR: $REGISTRY not found"
    exit 1
fi

echo ">> Generating stubs from $REGISTRY → $OUTPUT"

cat > "$OUTPUT" <<'HEADER'
-- AUTO-GENERATED by container/generate-stubs.sh — DO NOT EDIT MANUALLY.
-- Regenerate after adding functions to src/registry.rs.
--
-- These stubs cover st_* functions NOT already defined in
-- 0004-quackgis-types-stubs.sql or 0005-quackgis-aggregates.sql.
-- They use the bridge table pattern for DuckDB routing.

HEADER

# Functions already defined in other init scripts.
SKIP_FUNCS=$(grep -h -oP 'CREATE OR REPLACE (FUNCTION|AGGREGATE) \K(st_\w+)' \
    container/init.d/0004-quackgis-types-stubs.sql \
    container/init.d/0005-quackgis-aggregates.sql 2>/dev/null \
    | sort -u)

# Extract function names from registry.rs register_*! macro calls.
# Each macro type encodes the arity:
#   register_unary_geom!        → (geometry) → geometry
#   register_binary_geom!       → (geometry, geometry) → geometry
#   register_predicate!         → (geometry, geometry) → boolean
#   register_geom_double_to_geom! → (geometry, double) → geometry
#   register_geom_int_to_geom!  → (geometry, int) → geometry
#   ScalarFunctionBuilder       → parse manually
#
# For simplicity, generate stubs with the most common signatures.
# Multi-arg functions get variadic-compatible stubs.

COUNT=0

# Extract all st_* function names from register_*! macros.
grep -oP '(?:register_\w+)!\("((?:st_)\w+)"' "$REGISTRY" 2>/dev/null \
    | grep -oP 'st_\w+' | sort -u | while read -r func; do

    # Skip if already defined.
    if echo "$SKIP_FUNCS" | grep -qx "$func"; then
        continue
    fi

    # Determine signature from the macro type.
    # Look for the line containing this function name.
    line=$(grep "\"$func\"" "$REGISTRY" | head -1)

    if echo "$line" | grep -q 'register_predicate!'; then
        # (geometry, geometry) → boolean
        echo "CREATE OR REPLACE FUNCTION $func(g1 geometry, g2 geometry)"
        echo "RETURNS boolean LANGUAGE sql AS \$\$ SELECT $func(\$1, \$2) FROM quackgis._bridge LIMIT 1 \$\$;"
    elif echo "$line" | grep -q 'register_binary_geom!'; then
        # (geometry, geometry) → geometry
        echo "CREATE OR REPLACE FUNCTION $func(g1 geometry, g2 geometry)"
        echo "RETURNS geometry LANGUAGE sql AS \$\$ SELECT $func(\$1, \$2) FROM quackgis._bridge LIMIT 1 \$\$;"
    elif echo "$line" | grep -q 'register_geom_double_to_geom!'; then
        # (geometry, double) → geometry
        echo "CREATE OR REPLACE FUNCTION $func(g geometry, arg2 double precision)"
        echo "RETURNS geometry LANGUAGE sql AS \$\$ SELECT $func(\$1, \$2) FROM quackgis._bridge LIMIT 1 \$\$;"
    elif echo "$line" | grep -q 'register_geom_int_to_geom!\|register_geom_int2_to_geom!'; then
        # (geometry, int) → geometry
        echo "CREATE OR REPLACE FUNCTION $func(g geometry, arg2 int)"
        echo "RETURNS geometry LANGUAGE sql AS \$\$ SELECT $func(\$1, \$2) FROM quackgis._bridge LIMIT 1 \$\$;"
    elif echo "$line" | grep -q 'register_unary_geom!'; then
        # (geometry) → geometry
        echo "CREATE OR REPLACE FUNCTION $func(g geometry)"
        echo "RETURNS geometry LANGUAGE sql AS \$\$ SELECT $func(\$1) FROM quackgis._bridge LIMIT 1 \$\$;"
    elif echo "$line" | grep -q 'register_unary_geom_double!'; then
        # (geometry) → double
        echo "CREATE OR REPLACE FUNCTION $func(g geometry)"
        echo "RETURNS double precision LANGUAGE sql AS \$\$ SELECT $func(\$1) FROM quackgis._bridge LIMIT 1 \$\$;"
    elif echo "$line" | grep -q 'register_unary_geom_int!'; then
        # (geometry) → int
        echo "CREATE OR REPLACE FUNCTION $func(g geometry)"
        echo "RETURNS int LANGUAGE sql AS \$\$ SELECT $func(\$1) FROM quackgis._bridge LIMIT 1 \$\$;"
    elif echo "$line" | grep -q 'register_unary_geom_varchar!'; then
        # (geometry) → text
        echo "CREATE OR REPLACE FUNCTION $func(g geometry)"
        echo "RETURNS text LANGUAGE sql AS \$\$ SELECT $func(\$1) FROM quackgis._bridge LIMIT 1 \$\$;"
    elif echo "$line" | grep -q 'register_unary_geom_boolean!'; then
        # (geometry) → boolean
        echo "CREATE OR REPLACE FUNCTION $func(g geometry)"
        echo "RETURNS boolean LANGUAGE sql AS \$\$ SELECT $func(\$1) FROM quackgis._bridge LIMIT 1 \$\$;"
    else
        # Default: single geometry arg, geometry return.
        # ScalarFunctionBuilder calls with custom signatures fall here.
        echo "CREATE OR REPLACE FUNCTION $func(g geometry)"
        echo "RETURNS geometry LANGUAGE sql AS \$\$ SELECT $func(\$1) FROM quackgis._bridge LIMIT 1 \$\$;"
    fi

    echo ""
done >> "$OUTPUT"

COUNT=$(grep -c 'CREATE OR REPLACE FUNCTION' "$OUTPUT" || true)
echo ">> Generated $COUNT stub functions"
echo ">> Output: $OUTPUT ($(wc -l < "$OUTPUT") lines)"
