# SPDX-License-Identifier: Apache-2.0
# Repo-local tool/env bootstrap. Run `mise install`, then use `just --list`.

[env]
QUACKGIS_HOST = "127.0.0.1"
QUACKGIS_PORT = "5434"
QUACKGIS_CATALOG_PATH = "{{config_root}}/.tmp/dev/quackgis.db"
QUACKGIS_DATA_PATH = "{{config_root}}/.tmp/dev/data"
MARTIN_VERSION = "1.11.0"
MARTIN_BIN = "{{config_root}}/.tmp/bin/martin"
MARTIN_PORT = "3000"
QGIS_IMAGE = "docker.io/qgis/qgis:ltr-questing"
GEOSERVER_IMAGE = "docker.io/kartoza/geoserver:2.26.2"
KIND_CLUSTER = "quackgis"

[tools]
rust = "1.89.0"
"aqua:casey/just" = "1.53.0"
"aqua:kubernetes-sigs/kind" = "0.29.0"
"aqua:kubernetes/kubectl" = "1.33.2"
"aqua:helm/helm" = "3.18.3"
"cargo:cargo-nextest" = "latest"

[settings]
experimental = true
