{{- if .Values.persistence.pgdata.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  labels:
    {{- include "quackgis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.pgdata.size }}
  {{- if .Values.persistence.pgdata.storageClass }}
  storageClassName: {{ .Values.persistence.pgdata.storageClass | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.persistence.ducklake.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ducklake
  labels:
    {{- include "quackgis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.ducklake.size }}
  {{- if .Values.persistence.ducklake.storageClass }}
  storageClassName: {{ .Values.persistence.ducklake.storageClass | quote }}
  {{- end }}
{{- end }}
