apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quackgis.fullname" . }}-secret
  labels:
    {{- include "quackgis.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.quackgis.postgresPassword | quote }}
