apiVersion: v1
kind: Service
metadata:
  name: {{ include "quackgis.fullname" . }}
  labels:
    {{- include "quackgis.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgql
      protocol: TCP
      name: pgql
  selector:
    {{- include "quackgis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quackgis.fullname" . }}-headless
  labels:
    {{- include "quackgis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgql
      name: pgql
  selector:
    {{- include "quackgis.selectorLabels" . | nindent 4 }}
